<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [2]:
%%sql

select *
from sales
limit 5;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00

In [3]:
%%sql
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2              date
3           product
4             sales
5             store

### Table: `currencyexchange`

In [4]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'currencyexchange'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

    column_name          data_type
0          date               date
1  fromcurrency  character varying
2    tocurrency  character varying
3      exchange   double precision

### Table: `customer`

In [5]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'customer'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

      column_name          data_type
0     customerkey            integer
1      geoareakey            integer
2         startdt               date
3           enddt               date
4       continent  character varying
5          gender  character varying
6           title  character varying
7       givenname  character varying
8   middleinitial  character varying
9         surname  character varying
10  streetaddress  character varying
11           city  character varying
12          state  character varying
13      statefull  character varying
14        zipcode  character varying
15        country  character varying
16    countryfull  character varying
17       birthday               date
18            age            integer
19     occupation  character varying
20        company  character varying
21        vehicle  character varying
22       latitude   double precision
23      longitude   double precision

### Table: `date`

In [6]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'date'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

17 rows affected.

          column_name          data_type
0                date               date
1             datekey            integer
2                year            integer
3         yearquarter  character varying
4   yearquarternumber            integer
5             quarter  character varying
6           yearmonth  character varying
7      yearmonthshort  character varying
8     yearmonthnumber            integer
9               month  character varying
10         monthshort  character varying
11        monthnumber            integer
12          dayofweek  character varying
13     dayofweekshort  character varying
14    dayofweeknumber            integer
15         workingday            integer
16   workingdaynumber            integer

### Table: `product`

In [7]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'product'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

14 rows affected.

        column_name          data_type
0        productkey            integer
1       productcode            integer
2       productname  character varying
3      manufacturer  character varying
4             brand  character varying
5             color  character varying
6        weightunit  character varying
7            weight   double precision
8              cost   double precision
9             price   double precision
10      categorykey            integer
11     categoryname  character varying
12   subcategorykey            integer
13  subcategoryname  character varying

### Table: `sales`

In [8]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'sales'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

13 rows affected.

     column_name          data_type
0       orderkey            integer
1     linenumber            integer
2      orderdate               date
3   deliverydate               date
4    customerkey            integer
5       storekey            integer
6     productkey            integer
7       quantity            integer
8      unitprice   double precision
9       netprice   double precision
10      unitcost   double precision
11  currencycode  character varying
12  exchangerate   double precision

### Table: `store`

In [9]:
%%sql
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'store'
ORDER BY ordinal_position;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

11 rows affected.

     column_name          data_type
0       storekey            integer
1      storecode            integer
2     geoareakey            integer
3    countrycode  character varying
4    countryname  character varying
5          state  character varying
6       opendate               date
7      closedate               date
8    description  character varying
9   squaremeters   double precision
10        status  character varying

In [10]:
%%sql

select
  s.orderdate::date,
  COUNT(distinct s.customerkey) as number_of_customers,
  COUNT(distinct case when c.continent = 'Europe' then s.customerkey end) as ue_customers,
  COUNT(distinct case when c.continent = 'Australia' then s.customerkey end) as au_customers,
  COUNT(distinct case when c.continent = 'North America' then s.customerkey end) as na_customers
from
  sales s
  left join customer c on s.customerkey = c.customerkey
where
  extract(year from s.orderdate) = 2023
group by
  s.orderdate::date
order by
  s.orderdate;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  number_of_customers  ue_customers  au_customers  na_customers
0    2023-01-01                   12             6             1             5
1    2023-01-02                   49            15             3            31
2    2023-01-03                   64            17             3            44
3    2023-01-04                   78            28             4            46
4    2023-01-05                   87            22             8            57
..          ...                  ...           ...           ...           ...
359  2023-12-27                   73            26             6            41
360  2023-12-28                   75            24             7            44
361  2023-12-29                   55            19             4            32
362  2023-12-30                   91            25            16            50
363  2023-12-31                    9             1             0             8

[364 rows x 5 columns]

In [11]:
%%sql
select distinct(extract(year from orderdate)) from sales
;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

  extract
0    2017
1    2018
2    2024
3    2016
4    2023
5    2022
6    2019
7    2015
8    2021
9    2020

In [12]:
%%sql

select
  p.categoryname,
  SUM(s.quantity * s.netprice * s.exchangerate) as total_revenue,
  SUM(case when extract(year from s.orderdate) = 2022 then s.quantity * s.netprice * s.exchangerate end) as total_2022_revenue,
  SUM(case when extract(year from s.orderdate) = 2023 then s.quantity * s.netprice * s.exchangerate end) as total_2023_revenue
from
  sales s
  left join product p on s.productkey = p.productkey
group by
  p.categoryname
order by
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_revenue,total_2022_revenue,total_2023_revenue
0,Audio,5312898.10,766938.21,688690.18
1,Cameras and camcorders,18520360.66,2382532.56,1983546.29
2,Cell phones,32624265.72,8119665.07,6002147.63
3,Computers,90619022.05,17862213.49,11650867.21
4,Games and Toys,1668574.13,316127.30,270374.96
5,Home Appliances,26607245.54,6612446.68,5919992.87
6,"Music, Movies and Audio Books",10588311.00,2989297.28,2180768.13
7,TV and Video,20466861.38,5815336.61,4412178.23

In [13]:
%%sql
select
  orderdate,
  quantity,
  netprice,
  case
    when quantity >= 2 and netprice >= 100 then 'multiple high order'
    when netprice >= 100 then 'single high item'
    when quantity >= 2 then 'multi standard items'
    else 'single standard item'
  end
from
  sales
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  quantity  netprice                  case
0  2015-01-01         1     98.97  single standard item
1  2015-01-01         1    659.78      single high item
2  2015-01-01         2     54.38  multi standard items
3  2015-01-01         4    286.69   multiple high order
4  2015-01-01         7    135.75   multiple high order
5  2015-01-01         3    434.30   multiple high order
6  2015-01-01         1     58.73  single standard item
7  2015-01-01         3     74.99  multi standard items
8  2015-01-01         2    113.57   multiple high order
9  2015-01-01         1    499.45      single high item

In [14]:
%%sql

select
  PERCENTILE_CONT(.5) within group (order by (netprice * quantity * exchangerate)) as median
from
  sales;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  399.17

In [15]:
%%sql

with median_value as (
  select
  PERCENTILE_CONT(.5) within group (order by (netprice * quantity * exchangerate)) as median
from
  sales
)

select
  p.categoryname,
  sum(case when (s.netprice * s.quantity * s.exchangerate) < mv.median
      and extract(year from s.orderdate) = 2022 then
      (s.netprice * s.quantity * s.exchangerate) end) as total_low_revenue_2022,
  sum(case when (s.netprice * s.quantity * s.exchangerate) >= mv.median
      and extract(year from s.orderdate) = 2022 then
      (s.netprice * s.quantity * s.exchangerate) end) as total_high_revenue_2022,
  sum(case when (s.netprice * s.quantity * s.exchangerate) < mv.median
      and extract(year from s.orderdate) = 2023 then
      (s.netprice * s.quantity * s.exchangerate) end) as total_low_revenue_2023,
  sum(case when (s.netprice * s.quantity * s.exchangerate) >= mv.median
      and extract(year from s.orderdate) = 2023 then
      (s.netprice * s.quantity * s.exchangerate) end) as total_high_revenue_2023
from
  sales s
  left join product p on s.productkey = p.productkey,
  median_value mv
group by
  p.categoryname
order by
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_low_revenue_2022,total_high_revenue_2022,total_low_revenue_2023,total_high_revenue_2023
0,Audio,223932.63,543005.58,181847.01,506843.18
1,Cameras and camcorders,133801.07,2248731.49,105268.50,1878277.79
2,Cell phones,822810.73,7296854.34,738857.59,5263290.05
3,Computers,626333.55,17235879.94,592385.19,11058482.02
4,Games and Toys,232378.35,83748.95,206103.36,64271.60
5,Home Appliances,220196.04,6392250.64,177059.16,5742933.71
6,"Music, Movies and Audio Books",687403.38,2301893.90,576552.89,1604215.24
7,TV and Video,273532.94,5541803.66,166265.95,4245912.27

In [16]:
%%sql

with median_value as (
  select
  PERCENTILE_CONT(.5) within group (order by (netprice * quantity * exchangerate)) as median
from
  sales
), percentile_25_value as (
  select
    PERCENTILE_CONT(.25) within group (order by (netprice * quantity * exchangerate)) as q
  from
    sales
), percentile_75_value as (
  select
  PERCENTILE_CONT(.75) within group (order by (netprice * quantity * exchangerate)) as q
from
  sales
)

select
  p.categoryname,
  sum(case when (s.netprice * s.quantity * s.exchangerate) <= per_25.q then
      (s.netprice * s.quantity * s.exchangerate) end) as total_low_revenue,
  sum(case when (s.netprice * s.quantity * s.exchangerate) > mv.median and
  (s.netprice * s.quantity * s.exchangerate) <= per_75.q
  then (s.netprice * s.quantity * s.exchangerate) end) as total_medium_revenue,
  sum(case when (s.netprice * s.quantity * s.exchangerate) > per_75.q then
      (s.netprice * s.quantity * s.exchangerate) end) as total_high_revenue
from
  sales s
  left join product p on s.productkey = p.productkey,
  median_value mv, percentile_25_value per_25, percentile_75_value per_75
group by
  p.categoryname
order by
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_low_revenue,total_medium_revenue,total_high_revenue
0,Audio,234231.17,2476553.44,1071060.41
1,Cameras and camcorders,75826.07,2917149.11,14771578.64
2,Cell phones,388803.44,8733313.04,21005598.63
3,Computers,186898.20,9805294.19,78599971.59
4,Games and Toys,514304.79,287994.71,126142.52
5,Home Appliances,93670.73,3458941.36,22049525.06
6,"Music, Movies and Audio Books",600560.31,4117255.05,3602275.79
7,TV and Video,55881.15,3162061.63,16318760.07

In [17]:
%%sql

with percentile_values as (
  select
    PERCENTILE_CONT(.25) within group (order by (netprice * quantity * exchangerate)) as _25th_percentile_value,
    PERCENTILE_CONT(.5) within group (order by (netprice * quantity * exchangerate)) as median_value,
    PERCENTILE_CONT(.75) within group (order by (netprice * quantity * exchangerate)) as _75th_percentile_value
  from
    sales
)

select
  p.categoryname,
  case
    when (s.netprice * s.quantity * s.exchangerate) <= pv._25th_percentile_value then '3-Low'
    when (s.netprice * s.quantity * s.exchangerate) >= pv._75th_percentile_value then '1-High'
    else '2-Medium'
  end as rev_category,
  sum(s.netprice * s.quantity * s.exchangerate) as totoal_revenue
from
  sales s
  left join product p on s.productkey = p.productkey,
  percentile_values pv
group by
  p.categoryname,
  rev_category
order by
  p.categoryname;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

                     categoryname rev_category  totoal_revenue
0                           Audio       1-High      1071060.41
1                           Audio     2-Medium      4007606.53
2                           Audio        3-Low       234231.17
3         Cameras and camcorders        1-High     14771578.64
4         Cameras and camcorders      2-Medium      3672955.95
5         Cameras and camcorders         3-Low        75826.07
6                     Cell phones       1-High     21005598.63
7                     Cell phones     2-Medium     11229863.64
8                     Cell phones        3-Low       388803.44
9                       Computers       1-High     78599971.59
10                      Computers     2-Medium     11832152.27
11                      Computers        3-Low       186898.20
12                 Games and Toys       1-High       126142.52
13                 Games and Toys     2-Medium      1028126.82
14                 Games and Toys        3-Low       514304.79
15                Home Appliances       1-High     22049525.06
16                Home Appliances     2-Medium      4464049.74
17                Home Appliances        3-Low        93670.73
18  Music, Movies and Audio Books       1-High      3602275.79
19  Music, Movies and Audio Books     2-Medium      6385474.90
20  Music, Movies and Audio Books        3-Low       600560.31
21                   TV and Video       1-High     16319889.26
22                   TV and Video     2-Medium      4091090.98
23                   TV and Video        3-Low        55881.15

In [18]:
%%sql

select
  orderdate,
  DATE_TRUNC('MONTH', orderdate)::date
from
  sales
order by random()
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  date_trunc
0  2021-01-05  2021-01-01
1  2021-09-09  2021-09-01
2  2022-10-05  2022-10-01
3  2020-08-06  2020-08-01
4  2017-03-07  2017-03-01
5  2021-11-11  2021-11-01
6  2023-03-02  2023-03-01
7  2017-05-30  2017-05-01
8  2017-01-12  2017-01-01
9  2024-03-02  2024-03-01

In [19]:
%%sql

select
  DATE_TRUNC('MONTH', orderdate)::date as month,
  sum(netprice * quantity * exchangerate) as total_revenue,
  count(distinct customerkey) as Number_of_unique_customers
from
  sales
group by
  month
order by month;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

          month  total_revenue  number_of_unique_customers
0    2015-01-01      384092.66                         200
1    2015-02-01      706374.12                         291
2    2015-03-01      332961.59                         139
3    2015-04-01      160767.00                          78
4    2015-05-01      548632.63                         236
..          ...            ...                         ...
107  2023-12-01     2928550.93                        1484
108  2024-01-01     2677498.55                        1340
109  2024-02-01     3542322.55                        1718
110  2024-03-01     1692854.89                         877
111  2024-04-01      483851.39                         246

[112 rows x 3 columns]

In [20]:
%%sql

select
  to_char(orderdate, 'yyyy-month') year_month,
  sum(netprice * quantity * exchangerate) as total_revenue,
  count(distinct customerkey) as Number_of_unique_customers
from
  sales
group by
  year_month
order by year_month;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

112 rows affected.

         year_month  total_revenue  number_of_unique_customers
0    2015-april          160767.00                          78
1    2015-august         718538.62                         235
2    2015-december       922842.19                         367
3    2015-february       706374.12                         291
4    2015-january        384092.66                         200
..              ...            ...                         ...
107  2023-september     2622774.85                        1255
108  2024-april          483851.39                         246
109  2024-february      3542322.55                        1718
110  2024-january       2677498.55                        1340
111  2024-march         1692854.89                         877

[112 rows x 3 columns]

In [22]:
%%sql

select interval '1 month'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  interval
0  30 days

In [26]:
%%sql

select CURRENT_DATE;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

  current_date
0   2026-05-17

In [24]:
%%sql

select age(CURRENT_DATE, '2026-01-01')

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

       age
0 136 days

In [36]:
%%sql

select
  DATE_PART('year', orderdate) as year,
  round(avg(extract('day' from age(deliverydate, orderdate))), 2) as avg_processing_time,
  cast(SUM(netprice * quantity * exchangerate) as integer) as total_net_revenue
from
  sales
group by
  year
order by
  year;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

     year avg_processing_time  total_net_revenue
0 2015.00                1.10            7370979
1 2016.00                1.08           10383614
2 2017.00                0.83           13221339
3 2018.00                0.86           24667448
4 2019.00                0.81           31818096
5 2020.00                0.93           11218436
6 2021.00                1.36           21357977
7 2022.00                1.62           44864557
8 2023.00                1.75           33108566
9 2024.00                1.67            8396527

In [41]:
%%sql

select
  customerkey,
  orderdate,
  (netprice * quantity * exchangerate) as net_revenue,
  avg(netprice * quantity * exchangerate) over() total_avg_revenue
from
  sales
order by
  customerkey, orderdate
  limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey   orderdate  net_revenue  total_avg_revenue
0           15  2021-03-08      2217.41            1032.69
1          180  2018-07-28       525.31            1032.69
2          180  2023-08-28        71.36            1032.69
3          180  2023-08-28      1913.55            1032.69
4          185  2019-06-01      1395.52            1032.69
5          243  2016-05-19       287.67            1032.69
6          387  2018-12-21       619.77            1032.69
7          387  2018-12-21      1608.10            1032.69
8          387  2018-12-21        97.05            1032.69
9          387  2018-12-21        45.62            1032.69

In [44]:
%%sql

select
  customerkey,
  orderdate,
  (netprice * quantity * exchangerate) as net_revenue,
  avg(netprice * quantity * exchangerate) over(
    partition by(customerkey)
  ) customer_avg_revenue
from
  sales
order by
  customerkey, orderdate
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

   customerkey   orderdate  net_revenue  customer_avg_revenue
0           15  2021-03-08      2217.41               2217.41
1          180  2018-07-28       525.31                836.74
2          180  2023-08-28      1913.55                836.74
3          180  2023-08-28        71.36                836.74
4          185  2019-06-01      1395.52               1395.52
5          243  2016-05-19       287.67                287.67
6          387  2018-12-21       619.77                517.32
7          387  2018-12-21      1608.10                517.32
8          387  2018-12-21        97.05                517.32
9          387  2018-12-21        45.62                517.32

In [69]:
%%sql

select
  customerkey,
  orderdate,
  (netprice * quantity * exchangerate) as net_revenue,
  row_number() over(
    partition by(customerkey)
    order by netprice * quantity * exchangerate desc
  ) order_rank,
  SUM(netprice * quantity * exchangerate) over(
    partition by customerkey
    order by orderdate
  ) as customer_running_total,
  SUM(netprice * quantity * exchangerate) over(
    partition by customerkey
  ) as customer_total_revenue,
  100 *((netprice * quantity * exchangerate) / sum(netprice * quantity * exchangerate) over(
    partition by customerkey
  )) as percent_of_order_net_revenue
from
  sales
order by
  customerkey, orderdate
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderdate,net_revenue,order_rank,customer_running_total,customer_total_revenue,percent_of_order_net_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [91]:
%%sql

select
  orderdate,
  (orderkey * 10) + linenumber as order_line_item,
  (netprice * quantity * exchangerate) as net_revenue,
  sum(netprice * quantity * exchangerate) over(
    partition by orderdate
  ) as daily_net_revenue,
 100 * ((netprice * quantity * exchangerate) / sum(netprice * quantity * exchangerate) over(
    partition by orderdate
  )) as pfo_net_revenue
from
  sales
order by
  orderdate, net_revenue desc
limit 10;

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_item,net_revenue,daily_net_revenue,pfo_net_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26